"""New Migration

Revision ID: 2cf9436fcf90
Revises: 879f3d9972fc
Create Date: 2021-08-17 12:14:36.520905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf9436fcf90'
down_revision = '879f3d9972fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
