"""New Migration

Revision ID: b80f83918ef1
Revises: 2cf9436fcf90
Create Date: 2021-08-17 12:27:43.893030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80f83918ef1'
down_revision = '2cf9436fcf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
