"""New Migration

Revision ID: f883c6a1dca2
Revises: b80f83918ef1
Create Date: 2021-08-17 12:34:17.434141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f883c6a1dca2'
down_revision = 'b80f83918ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
